
export const ROUTES = {
  ONBOARDING: "onboarding",
  PROFILE: "profile",
  HOME: "home",
  MAINFLOW: "mainFlow",
  LOGIN: "loginMain",
  FORGOTPASSWORD: "forgotPassword",
  PICKADDRESS: "pickAddress",
  SETADDRESS: "setAddress",
  DELIVERY: "delivery",
  PICkUP: "pickup",
  OFFER: "offer",
  CART: "cart",
  PICKUPADDRESS: "pickupAddress",
  CHECKOUT: "checkout",
  VIEWITEMSDETAIL: "viewItemsDetail",
  DELIVERYDETAILS: "deliverDetails",
  PAYMENT: "payment",
  ORDERS: "orders",
  ACCOUNT: "myAccount",
  NOTIFICATION: "notification",
  SAVEDADDRESS: "SavedAddress",
  CHANGEPASSWORD: "ChangePassword",
  SAVEDPAYMENT: "SavedPayment",
  TC: "TermsCondition",
  PRIVACY: "Privacy",
  FAVORITES: "favorites",
  EDITPROFILE: "editProfile",
  VIEWPROFILE: "viewProfile",
  NITIFICATIONSETTINGS: 'notificationSettings'
};
