import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import { I18nManager } from "react-native";

// the translations
// (tip move them in a JSON file and import them)
const resources = {
  ar: {
    translation: {
      "Hello world": "مرحبا بالعالم",
      Login: "مرحبا بالعالم",
      "Get Started": "مرحبا بالعالم",
      "Riyadh Gallery Mall, Riyadh": "بهزادي تشوك لاهور",
      Delivery: "توصيل",
      "We deliver with-in 25 mins": "نحن نسلم مع الداخل 25 دقيقة",
      "Pick-Up": "تقديم الطعام",
      "Get your food on the go": "تذوق اللحظة دعنا نلبي احتياجاتك!",
      Catering: "يلتقط",
      "Savor the Moment, Let Us Cater to You!": "احصل على طعامك أثناء التنقل",
      "Todays Offers": "عروض اليوم",
      "see more": "شاهد المزيد",

      "Notification Settings": "إعدادات الإشعار",
      "General Notification": "إعلام عام",
      Common: "شائع",
      Sound: "صوت",
      "System & services update": "تحديث النظام والخدمات",
      "App Update": "تحديث التطبيق",
      "Bill Reminder": "تذكير الفاتورة",
      Promotion: "ترقية",
      "Discount Available": "خصم افايابلي",
      "Payment Request": "طلب الدفع",
      Others: "آحرون",
      "New Service Available": "خدمة جديدة متاحة",
      "New Tips Available": "نصائح جديدة متاحة",
      Search: "يبحث",
      Items: "عناصر",
      "Detail & Reviews": "التفاصيل والمراجعات",
      SAR: "سعودي ريال",
      "Estimated Delivery Time": "وقت التسليم المقدر",
      mins: "دقيقة",
      "Choose Variants": "اختر المتغيرات",
      "Choose at least one": "اختر واحدة على الأقل",
      "Choose Add-ons": "اختر اضافات",
      "Modifiers will be same for all the orders (quantity).":
        "ستكون المُعدِّلات هي نفسها لجميع الطلبات (الكمية).",
      "Modifier Heading": "عنوان المعدل",
      "Choose only one": "اختر واحدة فقط",
      Optional: "(خياري)",
      "Special Instructions": "تعليمات خاصة",
      Total: "المجموع",
      "Add to Cart": "أضف إلى السلة",
      "Buy Now": "اشتري الآن",
      "ARE YOU SURE?": "هل أنت متأكد?",
      "View Cart": "عرض عربة التسوق",
      "Add Anyway": "أضف على أي حال",
      "Adding this.": "ستؤدي إضافة",
      "DELIVERY ITEM": "عنصر التسليم",
      "will remove": "هذا إلى إزالة",
      "PICKUP ITEMS": "اصناف بيك اب",
      "from cart": "من سلة التسوق",
      "Added to Cart": "تمت الإضافة إلى عربة التسوق",
      "Your item was successfully added to Cart":
        "تم إضافة العنصر الخاص بك بنجاح إلى عربة التسوق.",
      "Explore Items": "اكتشف العناصر",
      Details: "تفاصيل",
      "Ratings & Reviews": "التقييمات والمراجعات",
      Description: "وصف",
      "Delivery Cart": "عربة التوصيل",
      "swipe on an item to delete or add to favourites":
        "اسحب على عنصر لحذفه أو إضافته إلى المفضلة",
      "Sub Total": "المجموع الفرعي",
      "Proceed to Checkout": "الشروع في الخروج",
      "Remove Item": "إزالة بند",
      "Are you sure you want to remove this item?":
        "هل أنت متأكد أنك تريد إزالة هذا العنصر؟",
      Cancel: "يلغي",
      Remove: "يزيل",
      "Delivery Details": "تفاصيل التسليم",
      Address: "عنوان",
      "Change Location": "تغيير الموقع",
      Change: "تغيير",
      "Order Summary": "ملخص الطلب",
      Checkout: "الدفع",
      "Add Items": "إضافة عناصر",
      VAT: "ضريبة القيمة المضافة",
      Discount: "تخفيض",
      Promos: "الملل",
      "Apply Promo": "تطبيق الترويج",
      "Proceed to Payment": "الشروع في دفع",
      Promo: "برومو",
      "Enter Promo Code": "إدخال الرمز الترويجي",
      Apply: "يتقدم",
      Payment: "قسط",
      "Choose Payment Method": "اختر وسيلة الدفع",
      Card: "بطاقة",
      "Cash on Delivery": "الدفع عند الاستلام",
      "Choose Card": "اختر البطاقة",
      "Add New Card": "إضافة بطاقة جديدة",
      "Place Order": "مكان الامر",
      "Card Holder Name": "إسم صاحب البطاقة",
      "Card Number": "رقم البطاقة",
      "Expiry Date": "تاريخ الانتهاء",
      CVC: "رمز التحقق من البطاقة (CVC)",
      "Save Card": "احفظ البطاقة",
      "Place your order": "ضع طلبك",
      "Please ensure that you have the exact amount of cash available at the time of delivery.":
        "يرجى التأكد من أن لديك المبلغ النقدي المتاح بالضبط في وقت التسليم.",
      "Order Placed": "تم الطلب",
      "Your order was successfully placed and will be delivered within 45 minutes.":
        "تم تقديم طلبك بنجاح وسيتم تسليمه في غضون 45 دقيقة.",
      "View Orders": "عرض الطلبات",
      "In Progress": "في تَقَدم",
      History: "تاريخ",
      "Delivery To": "تسليم الى",
      "Order Information Received": "تم استلام معلومات الطلب",
      "Order Preparing": "تحضير الطلب",
      Ready: "مستعد",
      Completed: "مكتمل",
      "Order Number": "رقم الأمر",
      "Estimated Delivery": "التوصيل المتوقع",
      "Total Cost": "التكلفة الإجمالية",
      "Inc. VAT": "شركة ضريبة القيمة المضافة",
      "Date & Time": "التاريخ والوقت",
      Method: "طريقة",
      DELIVERY: "توصيل",
      "Invoice ID": "هوية صوتية",
      "View Details": "عرض التفاصيل",
      Hide: "يخفي",
      Filters: "المرشحات",
      All: "الجميع",
      Pickup: "يلتقط",
      "Clear Filters": "مسح عوامل التصفية",
      "Apply Filters": "تطبيق المرشحات",
      "No notifications yet": "لا إخطارات حتى الآن",
      "You have no notifications yet, you will be notified about events or news in this section.":
        "ليس لديك إخطارات حتى الآن ، سيتم إخطارك بالأحداث أو الأخبار في هذا القسم.",
      "No internet Connection": "لا يوجد اتصال بالإنترنت",
      "Your internet connection is currently not available please check or try again.":
        "اتصالك بالإنترنت حاليً غير متوفر يرجى التحقق أو المحاولة مرة أخرى.",
      "No favorites yet": "لا مفضلات حتى الآن",
      "Hit the orange button down below to Create an order":
        "اضغط على الزر البرتقالي لأسفل أدناه لإنشاء طلب",
      "Item not found": "العنصر غير موجود",
      "Try searching the item with a different keyword.":
        "حاول البحث في العنصر باستخدام كلمة رئيسية مختلفة.",
      "No orders yet": "لا توجد طلبات حتى الآن",
      "No history yet": "لا يوجد سجل حتى الان",
      "Try again": "حاول ثانية",
      "Explore Products": "اكتشف المنتجات",

      //
      ////
      Home: "بيت",
      "My Account": "حسابي",
      Orders: "طلبات",
      Cart: "عربة التسوق",
      Profile: "حساب تعريفي",
      Offers: "عروض",
      Notifications: "إشعارات",
      "Privacy policy": "سياسة الخصوصية",
      "Terms & conditions": "سياسة الخصوصية",
      "Log-out": "خروج",
      "View Profile": "عرض الصفحة الشخصية",
      "Marvis Ighedosa": "مارفيس إيجيدوسا",
      "dosamarvis@gmail.com": "Dosamarvis@gmail.com",
      "Edit Profile": "تعديل الملف الشخصي",
      "Full Name": "الاسم الكامل",
      Email: "بريد إلكتروني",
      "Date of birth": "تاريخ الميلاد",
      Contact: "اتصال",
      "15/02/1994": "15/02/1994",
      "09130-233-1234": "09130-233-1234",
      "Riyadh Al Ta aown Dist": "بهزادي تشوك ، شارع اي بي سي ، لاهور",

      "Cart :": "عربة التسوق",
      "Swipe on an item to delete or add to favourites":
        "اسحب على عنصر لحذفه أو إضافته إلى المفضلة",
      "Proceed to": "الشروع في الخروج",
      Notification: "إشعارات",
      Today: "اليوم",
      Yesterday: "أمس",
      "Promo Code": "رمز ترويجي",
      "Convallis cursus quam mauris ut sed sit at leo ac morbi in est.":
        "عرض جديد: احصل على خصم 50% على جميع المنتجات!",

      "1. Types data we collect": "1. الكشف عن بياناتك الشخصية",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.":
        ".مﻮﺠﻬﻟا ﺮﻤﺘﺳاو ﻮﻫ ﻢﺗو ,ﻢﺗ ﺖﺤﺗ ﺎﻴﻧﺎﻤﻟاو ﺐﻧﺎﺠﻟﺎﺑ ﺦﻳرﺎﺗ .ﻦﻋ ﺾﻌﺑ ،ﺎﻳﺪﻴﺒﻴﻜﻳو رﺎﺘﺴﻟا ,يأ نﻮﻳﺪﻟاو لاﺪﺒﺘﺳا ﺔﻤﻴﺴﺟ ﺎﻬﻟ .ﺔﺿرﺎﻌﻣ ﻪﻠﻟا ﻚﻠﺗ ـﺑ ,ﻲﻓ تاذ ،ﻊﻴﺑﺮﻟا مزُه ,ﻢﺛ ،ةﺪﻳﺪﺠﻟا رﺎﺘﺴﻟا ﺢﻔﺼﺗ ﻮﻳإ .ﻞﻌﺟ ٣٠ جرﻮﺟ ضﺮﻔﺑ لﻮﺧد ,ءﻲﺷ ﺔﻴﻜﻳﺮﻣﺄﻟا ثاﺪﺤﺘﺳﺎﺑ ﻢﻬﺘﻀﺒﻗ ﻊﻣ ,اﺪﻨﻟﻮﺑو ﻦﻴﻓﺮﻄﻟا رازوأ يأ ﺮﺳأ .ﻦﻋ يﺪﻨﻟﻮﺒﻟا ىّﻦﺴﺘﻳ ﺔﻠﻤﻌﻟ ﻰﻟا .تءﺎﺑو ﺔﻳﺎﻬﻧ ﺪﻌﺒﻓ ﻦﻜﻣ نأ ,ﺐﺒﺴﻟا ضرﺄﻟا ﺪﻘﻓ ﻦﻣ ,ﻞﺑ تاﺪﻌﻤﻟاو ةدﺎﻴﻘﺑ ةدﺎﻗ لود",

      "Select Branch": "حدد الفرع",
      "Nearby Branch": "فرع قريب",
      "All Branches": "جميع الفروع",

      Language: "لغة",
      Default: "تقصير",
      Save: "يحفظ",

      "Food for Everyone": "طعام لأجل الجميع",

      "Add your location": "أضف موقعك",
      "Save As": "حفظ باسم",
      // 'Save As': 'حفظ باسم',
      "Skip For Now": "تخطي في الوقت الراهن",
      "Forgot Password?": "هل نسيت كلمة السر",
      Password: "كلمة المرور",

      "Saved Addresses": "هل نسيت كلمة السر",
      "To reset your password, please enter your email address below. We will then send you an email containing a link to reset your password.":
        "لإعادة تعيين كلمة المرور الخاصة بك.  يرجى إدخال عنوان بريدك الإلكتروني أدناه. سنرسل لك بعد ذلك رسالة بريد إلكتروني تحتوي على رابط لإعادة تعيين كلمة المرور الخاصة بك.",

      "Send Reset Link": "أرسل رابط إعادة التعيين",
      Username: "اسم المستخدم",
      "Email Address": "عنوان البريد الإلكتروني",
      "Phone Number": "رقم التليفون",
      "Confirm Password": "تأكيد كلمة المرور",

      "Sign Up": "اشتراك",
      "View  Profile": "عرض الصفحة الشخصية",
      "General Settings": "الاعدادات العامة",
      "English (Default)": "العربية (افتراضي)",
      "Saved Address": "العنوان المحفوظ",
      "Change Password": "تغيير كلمة المرور",
      "Payment Method": "طريقة الدفع او السداد",
      Resources: "موارد",
      Help: "يساعد",
      "Terms & Conditions": "البنود و الظروف",
      Favorites: "سياسة الخصوصية",
      "Replace Photo": "استبدال الصورة",
      Discard: "ينبذ",
      "Save Changes": "حفظ التغييرات",
      "Please, provide your name!": "من فضلك أدخل اسمك",
      "Please, provide your email!": "من فضلك ، قدم بريدك الإلكتروني",
      "Please, provide your date of birth!": "من فضلك ، قدم تاريخ ميلادك",
      "Please, provide valid phone number!": "من فضلك ، أدخل رقم هاتف صحيح",
      "Your Name": "اسمك",
      "Please, provide card holder name!": "من فضلك ، قدم اسم حامل البطاقة",
      "Please, provide card number!": "من فضلك ادخل رقم البطاقة",
      "Please, provide expiry date!": "يرجى تقديم تاريخ انتهاء الصلاحية",
      "Please, provide CVC": "من فضلك ، قم بتوفير رمز التحقق من البطاقة (CVC)",
      "Please, provide promo code!": "من فضلك ، قدم الرمز الترويجي",
      "Please, select date!": "الرجاء تحديد التاريخ",
      "Invalid Email": "بريد إلكتروني خاطئ",
      "Email Required": "البريد الإلكتروني (مطلوب",
      "Password Required": "كلمة المرور مطلوبة",
      "Password too short": "كلمة المرور أقصر مما يجب",
      "Password must be a combination of letters and numbers":
        "يجب أن تتكون كلمة المرور من مجموعة من الأحرف والأرقام",
      Quantity: "كمية",
      Cash: "نقدي",
    },
  },
};

i18n
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    fallbackLng: 'en',
    resources,
    lng: I18nManager.isRTL ? "ar" : "en",

    keySeparator: false, // we do not use keys in form messages.welcome

    interpolation: {
      escapeValue: false, // react already safes from xss
    },
  });

export default i18n;
